import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

const fontSerif = Merriweather({
  subsets: ["latin", "vietnamese"],
  display: "swap",
  style: ["normal"],
  weight: ["400", "500", "600"],
  adjustFontFallback: false,
  variable: "--font-serif"
});

const fontDisplay = Inter({
  subsets: ["latin", "vietnamese"],
  display: "swap",
  style: ["normal"],
  weight: ["400", "500", "600"],
  adjustFontFallback: false,
  variable: "--font-display"
});

export const metadata: Metadata = {
  title: "ThaiVan Blog",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body
          className={`${fontSerif.variable} ${fontDisplay.variable} antialiased`}
        >
          <>
            {children}
            <Toaster />
          </>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
