name: Deploy to railway

on:
  push:
    branches: [master]

jobs:
  all-checks:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v3

      - name: Run build
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Run test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 40a00ac4-cf2a-4739-baac-e7bea3b1cbc7
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }}
